Fixed bug #KUSU-33, also added status dialog boxes for confirmation screens (progress toward #KUSU-54). Plus, exception trace backs are stored to /tmp/kusu/exception.dump. (#KUSU-58)

diff --git a/src/dists/fedora/6/i386/updates.img/anaconda b/src/dists/fedora/6/i386/updates.img/anaconda
--- a/src/dists/fedora/6/i386/updates.img/anaconda
+++ b/src/dists/fedora/6/i386/updates.img/anaconda
@@ -25,8 +25,8 @@ source /opt/kusu/bin/kusuenv.sh
 
 # launch the Kusu Installer
 /usr/bin/python /opt/kusu/bin/installer
-
-if [ $? -eq 0 ]; then 
+EXIT_CODE=$?
+if [ $EXIT_CODE -eq 0 ]; then 
     # Unset kusu bits
     for key in `/usr/bin/env | /usr/bin/awk -F= '{print $1}' | grep KUSU`; do 
         unset $key > /dev/null 2>&1
@@ -44,6 +44,14 @@ if [ $? -eq 0 ]; then
     # exec the real anaconda
     # Need a better to replace existing -m and --kickstart option in $@
     /usr/bin/anaconda "$@" -m http://127.0.0.1/ --kickstart /tmp/kusu/install_script ;
+elif [ $EXIT_CODE -eq 1 ]; then
+    # an unknown exception has occurred. Give user an option to copy out log+dump
+    echo "An internal program error has occurred."
+    echo "A log of the session can be found in /tmp/kusu/kusu.log"
+    echo "A dump of the error can be found in /tmp/kusu/exception.dump";
+elif [ $EXIT_CODE -eq 2 ]; then
+    # exit code 2 means user chose to exit
+    echo "Exiting on request. Please standby for reboot...";
 else
     # in case of problem with the Kusu Installer, we halt
     echo "Something has gone very wrong. Restarting!";
