Checkpoint...  mostly functional now

diff --git a/src/kits/lsf/S11lsf-genconfig b/src/kits/lsf/S11lsf-genconfig
--- a/src/kits/lsf/S11lsf-genconfig
+++ b/src/kits/lsf/S11lsf-genconfig
@@ -1,9 +1,17 @@
 #!/bin/sh
 
 GENCONFIG=""
-VERSION="1_0"
-# Generate Lava host configuration for installer only.
-if [ -f /opt/kusu/bin/genconfig ]; then 
+LSFVERSION="7_0_1"
+EGOVERSION="1_2"
+CLUSTERNAME="master"
+
+LSF_CONFDIR="/opt/lsf/conf"
+EGO_CONFDIR="/opt/lsf/ego/kernel/conf"
+
+MASTER_NODEGROUP="lsf-master-candidate"
+
+# Generate LSF host configuration for installer only.
+if [ -f /opt/kusu/bin/genconfig ]; then
    export PYTHONPATH=/opt/kusu/lib/python:$PYTHONPATH
    GENCONFIG="/opt/kusu/bin/genconfig"
 fi
@@ -16,32 +24,70 @@ if [ -f /usr/bin/genconfig ]; then
 fi
 
 if [ -z $GENCONFIG ]; then
-   exit
+	echo "Error: unable to locate genconfig"
+	exit 1
 fi
 
-# Make directories
-mkdir -p /opt/lava/conf/lsbatch/lava/configdir
+[ -d /etc/cfm/$MASTER_NODEGROUP ] || mkdir -p /etc/cfm/$MASTER_NODEGROUP
+if [ $? -ne 0 ]; then
+	echo "Error creating directory /etc/cfm/$MASTER_NODEGROUP"
+	exit 1
+fi
 
-$GENCONFIG lavacluster_$VERSION cluster > /opt/lava/conf/lsf.cluster.lava
-$GENCONFIG lavacluster_$VERSION batch > /opt/lava/conf/lsbatch/lava/configdir/lsb.hosts
-$GENCONFIG lavaconf_$VERSION master > /opt/lava/conf/lsf.conf
-$GENCONFIG lavahosts_$VERSION > /opt/lava/conf/hosts
+INSTALLER_SRC_CFMDIR=$( $GENCONFIG nodegroups ngid=1 )
+if [ -z "$INSTALLER_SRC_CFMDIR" ]; then
+	echo "Fatal error: unable to find installer nodegroup"
+	exit 1
+fi
 
-groupadd lavaadmin
-adduser -d "/home/lavaadmin" -g lavaadmin -m lavaadmin
+cp -ar /etc/cfm/$INSTALLER_SRC_CFMDIR/* /etc/cfm/$MASTER_NODEGROUP
+if [ $? -ne 0 ]; then
+	echo "Error copying files from /etc/cfm/$INSTALLER_SRC_CFMDIR to /etc/cfm/$MASTER_NODEGROUP"
+fi
 
-chown -R lavaadmin:lavaadmin /opt/lava/conf/*
+# Create files into CFM directory
+CFM_EGO_CONFDIR="/etc/cfm/$MASTER_NODEGROUP""$EGO_CONFDIR"
+
+[ -d "$CFM_EGO_CONFDIR" ] || mkdir -p "$CFM_EGO_CONFDIR"
+if [ $? -ne 0 ]; then
+	echo "Error creating directory $CFM_EGO_CONFDIR"
+	exit 1
+fi
+
+CFM_LSF_CONFDIR="/etc/cfm/$MASTER_NODEGROUP""$LSF_CONFDIR"
+
+[ -d "$CFM_LSF_CONFDIR" ] || mkdir -p "$CFM_LSF_CONFDIR"
+if [ $? -ne 0 ]; then
+	echo "Error creating directory $CFM_LSF_CONFDIR"
+	exit 1
+fi
+
+$GENCONFIG lsfcluster_$LSFVERSION $CLUSTERNAME cluster >$CFM_EGO_CONFDIR/ego.cluster.$CLUSTERNAME
+
+$GENCONFIG egoshared_$EGOVERSION $CLUSTERNAME >$CFM_EGO_CONFDIR/ego.shared
+
+$GENCONFIG lsfconf_$LSFVERSION $CLUSTERNAME master >$CFM_LSF_CONFDIR/lsf.conf
+$GENCONFIG egoconf_$EGOVERSION $CLUSTERNAME master >$CFM_EGO_CONFDIR/ego.conf
 
 # Generate CFM symlinks
-for i in `sqlrunner -q 'SELECT ngname FROM nodegroups WHERE ngid != 1 AND ngid < 5'`; do
-    cd /etc/cfm/$i
-    if [ ! -d /etc/cfm/$i/opt/lava/conf/lsbatch/lava/configdir ]; then
-       mkdir -p /etc/cfm/$i/opt/lava/conf/lsbatch/lava/configdir
-    fi
+for ng in $( sqlrunner -q 'SELECT ngname FROM nodegroups WHERE ngid != 1 AND ngid < 5' ); do
+	CFM_LSF_CONFDIR="/etc/cfm/$ng""$LSF_CONFDIR"
+	CFM_EGO_CONFDIR="/etc/cfm/$ng""$EGO_CONFDIR"
 
-# Lava master slave configuration only
-$GENCONFIG lavaconf_$VERSION slave > /etc/cfm/$i/opt/lava/conf/lsf.conf
+	[ -d "$CFM_LSF_CONFDIR" ] || mkdir -p "$CFM_LSF_CONFDIR"
+	if [ $? -ne 0 ]; then
+		echo "Error creating directory $CFM_LSF_CONFDIR"
+		exit 1
+	fi
 
+	[ -d "$CFM_EGO_CONFDIR" ] || mkdir -p "$CFM_EGO_CONFDIR"
+	if [ $? -ne 0 ]; then
+		echo "Error creating directory $CFM_EGO_CONFDIR"
+		exit 1
+	fi
+
+	$GENCONFIG lsfconf_$LSFVERSION $CLUSTERNAME slave >$CFM_LSF_CONFDIR/lsf.conf
+	$GENCONFIG egoconf_$EGOVERSION $CLUSTERNAME slave >$CFM_EGO_CONFDIR/ego.conf
 done
 
-rm -rf /etc/rc.kusu.d/S10lava-genconfig
+rm -f /etc/rc.kusu.d/S11lsf-genconfig
